spring:
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://localhost:5432/library
    username: root
    password: root

  liquibase:
    enabled: true
    drop-first: true

  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
